[package]
name = "sip_rld"
version = "0.2.3"
authors = ["rolledm <rolledm@gmail.com>"]
edition = "2018"
description = "Library for work with SIP protocol"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
